Pull request for the authentication project.
firmoholanda/members-only pull request #2
Opened 2020-02-18 19:40 UTC by RoodzFernando

We have implemented the things below.
- A user model and the controllers
- Add the different views and forms
- Add a signup and login forms. 
- A post model
- Add the authorization required for a logged user.

2020-02-18 21:32 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello @RoodzFernando @firmoholanda 

Well done job! IT's correctly working but there are some requirements that need to be met.

1. As indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_create_requirement.png), It has a `#before_create` callback that generates a :remember_token 

2. Don't think about using `session`. The `cookies` is sufficient.

3. Please, fix all the stickler's errors.

4. Read the comment below.

Kindly make the suggested changes and submit a new code review request.
Thanks

Mael FOSSO

2020-02-18 21:32 UTC, maelfosso commented on app/models/user.rb
> +  end
Not really needed. Use `Digest::SHA1.hexdigest` which is required in project specification

2020-02-18 21:32 UTC, maelfosso commented on app/helpers/sessions_helper.rb
> +    session[:user_id] = user.id
Forget about using `session`. Only `cookies` is needed.

2020-02-18 21:32 UTC, maelfosso commented on app/helpers/sessions_helper.rb
> +    end
It's too long.
Kindly, consider only `cookies` and check whether or not an user with the `cookies.permanent[:remember_token]` exists

2020-02-18 21:32 UTC, maelfosso commented on app/helpers/sessions_helper.rb
> +    # user.forget
Remove comment

2020-02-20 01:39 UTC, mcrd25 approved these changes
# Changes Approved! 💪 🤓 🎊 

Hi [Holanda](@firmoholanda )! Hi [Fernando](@RoodzFernando )! 👋 

Good job with the changes! I see no more for further review! 😄 

I do however have some optional suggestions.

#### Additional Suggestions
- Currently, a user can edit another user's info. Maybe this should not be the case [OPTIONAL]
- The create post button should be seen right away, I almost missed it [OPTIONAL]
- Sign up button should not be shown when a user is logged in [OPTIONAL]

***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

2020-02-20 12:45 UTC, merged